name: ADASS-2025-solar-wavecal-tutorial
channels:
  - defaults
dependencies:
  - python=3.11
  - astropy>=6.1
  - numpy>=1.26.4
  - pooch>=1.8.0
  - pydantic>=2.0
  - scipy>=1.13.0
  - lmfit>=1.3.0
  - jupyterlab
  - matplotlib